# https://gitea.com/gitea/helm-chart/releases
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: kube-system
spec:
  repo: "https://dl.gitea.io/charts/"
  chart: gitea
  version: 5.0.1
  targetNamespace: gitea
  valuesContent: |-
    gitea:
      config:
        APP_NAME: "Anchorlytics Code"
        server:
          PPROF_ENABLED: true
      admin:
        existingSecret: gitea-admin
      cache:
        builtIn:
          enabled: true
      metrics:
        enabled: true
    persistence:
      enabled: true
      size: 20Gi
    postgresql:
      persistence:
        enabled: true
    ingress:
      enabled: true
      className: vpn
      hosts:
      - code.vpn.seanho.com
      tls:
      - secretName: gitea-tls
        hosts:
        - code.vpn.seanho.com
      annotations:
        cert-manager.io/cluster-issuer: le-prod
