
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  repo: "https://kubernetes.github.io/ingress-nginx"
  chart: ingress-nginx
  version: 3.24.0
  targetNamespace: ingress-nginx
  valuesContent: |-
    controller:
      kind: DaemonSet
      nodeSelector:
        role: ingress
      service:
        type: NodePort
        nodePorts:
          http: 32080
          https: 32443
