# https://artifacthub.io/packages/helm/cert-manager/cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: "https://charts.jetstack.io"
  chart: cert-manager
  version: 1.6.1
  targetNamespace: cert-manager
  valuesContent: |-
    installCRDs: true
    prometheus:
      enabled: false
      servicemonitor:
        enabled: false
    ingressShim:
      defaultIssuerName: le-prod
      defaultIssuerKind: ClusterIssuer
    extraArgs:
    - "--dns01-recursive-nameservers-only"
    - "--dns01-recursive-nameservers=1.1.1.1:53"
